#!/bin/sh

function mkcd() {
    mkdir -p $@ && cd ${@:$#}
}

function mkpw() {
    tr -dc ${2:-'[:alnum:]'} < /dev/urandom | head -c ${1:-32} && echo
}

function takegit() {
    git clone --depth 1 $@
    if (( $# == 2 )); then
        cd "$2"
    else
        cd $(basename $1 .git)
    fi
}

function cdtmp() {
    cd -- "$(mktemp -d /tmp/demo-XXXXX)"
}

# list only the /tmp/demo-XXXXX dirs created by cdtmp, then cd into the chosen one
function cddemo() {
    local dir="$(fd -t d --max-depth 1 --no-ignore --hidden '^demo-[A-Za-z0-9]{5}$' /tmp \
        | fzf --preview 'tree -a -L 1 -C --dirsfirst {}')"
    if [ -n "$dir" ]; then
        cd -- "$dir"
    else
        return 1
    fi
}

function fh() {
    eval $(fc -l 1 | fzf +s --tac | sed 's/ *[0-9]* *//')
}

function history-stats() {
    if [ -z "$1" ]; then
        entries=10
    else
        entries="$1"
    fi
    fc -l 1 \
        | awk '{ CMD[$2]++; } END { for (a in CMD) print CMD[a] " " CMD[a]*100/NR "% " a }' \
        | grep -v "./" \
        | column -c3 -s " " -t \
        | sort -nr \
        | nl \
        | head -n "$entries"
}

function bt() {
    local num_folders_we_are_in=$(echo $PWD | grep -o '/' | wc -l)

    if [[ $1 =~ ^[1-9]$ ]]; then
        local dest="./"
        if [[ $1 -gt $num_folders_we_are_in ]]; then
            print -- "bd: Error: Can not go up $1 times (not enough parent directories)"
            return 1
        fi
        for ((i = 1; i <= $1; i++)); do
            dest+="../"
        done
        cd $dest
        return 0
    else
        cd "${PWD%/$1/*}/$1"
    fi
}

function urlencode() {
    python3 -c 'import sys, urllib.parse as parser; print(parser.quote_plus(sys.stdin.read()))'
}

function urldecode() {
    python3 -c 'import sys, urllib.parse as parser; print(parser.unquote_plus(sys.stdin.read()))'
}

# generate random jwt secret key
function secretkeygen() {
    node -e "console.log(require('crypto').randomBytes(32).toString('hex'))" | tee /dev/tty | xclip -r -sel clip
}

function vdh() {
    url="${@: -1}"
    case "$url" in
        *youtube*)   yt-dlp --config-locations ~/.config/yt-dlp/youtube.conf "$@" ;;
        *bilibili*)  yt-dlp --config-locations ~/.config/yt-dlp/bilibili.conf "$@" ;;
        *)           echo 'Unsupported url'; return 1 ;;
    esac
}

function sdh() {
    url="${@: -1}"
    case "$url" in
        *youtube*)   yt-dlp --write-auto-subs --sub-lang en --skip-download --config-locations ~/.config/yt-dlp/youtube.conf "$@" ;;
        *bilibili*)  yt-dlp --write-auto-subs --sub-lang en --skip-download --config-locations ~/.config/yt-dlp/bilibili.conf "$@" ;;
        *)           echo 'Unsupported url'; return 1 ;;
    esac
}

function adh() {
    url="${@: -1}"
    case "$url" in
        *youtube*)   yt-dlp --config-locations ~/.config/yt-dlp/audio/youtube.conf "$@" ;;
        *bilibili*)  yt-dlp --config-locations ~/.config/yt-dlp/audio/bilibili.conf "$@" ;;
        *)           echo 'Unsupported url'; return 1 ;;
    esac
}

function update-mirror() {
    sudo reflector --verbose \
        --country China \
        --protocol https \
        --age 12 \
        --latest 5 \
        --sort rate \
        --save /etc/pacman.d/mirrorlist
}

function weather-report() {
    curl -H "Accept-Language: zh" "wttr.in/Shenzhen+Longhua?1QF"
}

# shell wrapper that provides the ability to change the current working directory when exiting Yazi
function yy() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp" &> /dev/null
}

function rr() {
	local tmp="$(mktemp -t "ranger-cwd.XXXXXX")"
    ranger --choosedir="$tmp" "$@"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp" &> /dev/null
}

# goto git repo root folder
function gr() {
    local relative_path="$(git rev-parse --show-cdup)"
    if [ -n "$relative_path" ]; then
        cd "$relative_path"
    fi
}

# goto whatever is the forefront Finder window. reference from [https://github.com/sapegin/dotfiles]
function cdf() {
    cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')"
}

function google() {
    echo "Googling: $@"
    for term in $@; do
        search="$search%20$term"
    done
    xdg-open "https://www.google.com/search?q=$search"
}

# cd to a parent directory.
function ...() {
    new_dir="$(explode_path | tail -n +2 | fzf --prompt 'Parents > ' --preview 'tree -a -L 1 -C --dirsfirst {}')"
    if [ -n "$new_dir" ]; then
        cd "$new_dir"
    else
        return 1
    fi
}
