#!/bin/sh

export GPG_TTY=$(tty)

export SUDO_PROMPT="[sudo] password for $(whoami): 🔐 "

# fzf
export FZF_COMPLETION_TRIGGER='\'
export FZF_DEFAULT_COMMAND='fd --hidden --exclude .git --follow --type f'
export FZF_DEFAULT_OPTS=" \
--height 40% --border --reverse --inline-info --pointer="👉" \
--color=dark \
--color=gutter:#2e2e2e \
--color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:-1,hl+:#ffaf5f \
--color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7
"
export FZF_CTRL_T_COMMAND='fd -t f -H -L -E={.git,.idea,.vscode,node_modules,dist} --strip-cwd-prefix'
export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range=:50 {}'"
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window up:3:hidden:wrap"
export FZF_ALT_C_OPTS="--preview 'tree -C --dirsfirst {}'"

# asdf
export ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME}/asdf/asdfrc"
export ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=".config/asdf/tool-versions"
export PATH="$ASDF_DATA_DIR/shims:$PATH"

# npm
export PATH="${XDG_DATA_HOME}/npm/bin:$PATH"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
