#!/bin/sh

# export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
export PATH="$PATH:$HOME/.local/bin"

# default apps
export EDITOR="nvim"
export TERMINAL="foot"
export BROWSER="google-chrome-stable"

# ~/ clean-up
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/X11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"

export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export MYCLI_HISTFILE="${XDG_CACHE_HOME}/mycli/history"
export VSCODE_PORTABLE="$XDG_CONFIG_HOME/vscode"
export GDBHISTFILE="$XDG_CACHE_HOME/gdb/gdb_history"
export CGDB_DIR="$XDG_CONFIG_HOME/cgdb"
export CALCHISTFILE="$XDG_CACHE_HOME/calc_history"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME}/password-store"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite3/sqlite_history"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"

export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export QT_QPA_PLATFORMTHEME="qt6ct"	# Have QT use gtk2 theme.
export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1
export QT_SCALE_FACTOR=1.4
export GROFF_NO_SGR=1

export CARGO_HOME="$XDG_DATA_HOME"/cargo
export REDISCLI_HISTFILE="$XDG_DATA_HOME"/redis/rediscli_history
export REDISCLI_RCFILE="$XDG_CONFIG_HOME"/redis/redisclirc

# colorize man pages
export LESS=-R
export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;44;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;32m'

# environ for fcitx
# export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

# if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
#     exec ~/.config/hypr/wrappedhl
# fi

# if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
#     niri-session
# fi

export WLR_NO_HARDWARE_CURSORS=1
if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    exec sway
fi
